# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):    #setting up user interface
        Form.setObjectName("Form")
        Form.resize(800, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(800, 500))
        Form.setMaximumSize(QtCore.QSize(800, 500))
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(290, 11, 261, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.saveWeightsBtn = QtWidgets.QPushButton(self.tab_1)
        self.saveWeightsBtn.setGeometry(QtCore.QRect(150, 45, 93, 28))
        self.saveWeightsBtn.setObjectName("saveWeightsBtn")
        self.trainBtn = QtWidgets.QPushButton(self.tab_1)
        self.trainBtn.setGeometry(QtCore.QRect(150, 10, 93, 28))
        self.trainBtn.setObjectName("trainBtn")
        self.batchSizeSpBox = QtWidgets.QSpinBox(self.tab_1)
        self.batchSizeSpBox.setGeometry(QtCore.QRect(90, 47, 42, 22))
        self.batchSizeSpBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.batchSizeSpBox.setMinimum(1)
        self.batchSizeSpBox.setProperty("value", 8)
        self.batchSizeSpBox.setObjectName("batchSizeSpBox")
        self.batchSizeLbl = QtWidgets.QLabel(self.tab_1)
        self.batchSizeLbl.setGeometry(QtCore.QRect(10, 47, 71, 20))
        self.batchSizeLbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.batchSizeLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.batchSizeLbl.setObjectName("batchSizeLbl")
        self.epochsSpBox = QtWidgets.QSpinBox(self.tab_1)
        self.epochsSpBox.setGeometry(QtCore.QRect(90, 12, 42, 22))
        self.epochsSpBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.epochsSpBox.setMinimum(1)
        self.epochsSpBox.setProperty("value", 16)
        self.epochsSpBox.setObjectName("epochsSpBox")
        self.epochsLbl = QtWidgets.QLabel(self.tab_1)
        self.epochsLbl.setGeometry(QtCore.QRect(10, 12, 71, 20))
        self.epochsLbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.epochsLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.epochsLbl.setObjectName("epochsLbl")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.loadWeightsBtn = QtWidgets.QPushButton(self.tab)
        self.loadWeightsBtn.setGeometry(QtCore.QRect(150, 10, 93, 28))
        self.loadWeightsBtn.setObjectName("loadWeightsBtn")
        self.predictBtn = QtWidgets.QPushButton(self.tab)
        self.predictBtn.setGeometry(QtCore.QRect(150, 45, 93, 28))
        self.predictBtn.setObjectName("predictBtn")
        self.tabWidget.addTab(self.tab, "")
        self.outputLbl = QtWidgets.QLabel(Form)
        self.outputLbl.setGeometry(QtCore.QRect(15, 115, 43, 16))
        self.outputLbl.setObjectName("outputLbl")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(11, 137, 781, 351))
        self.plainTextEdit.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.plainTextEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.loadDataBtn = QtWidgets.QPushButton(Form)
        self.loadDataBtn.setGeometry(QtCore.QRect(30, 40, 93, 28))
        self.loadDataBtn.setObjectName("loadDataBtn")
        self.perceptronsSpBox = QtWidgets.QSpinBox(Form)
        self.perceptronsSpBox.setGeometry(QtCore.QRect(150, 40, 42, 22))
        self.perceptronsSpBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.perceptronsSpBox.setSuffix("")
        self.perceptronsSpBox.setMinimum(1)
        self.perceptronsSpBox.setMaximum(256)
        self.perceptronsSpBox.setProperty("value", 12)
        self.perceptronsSpBox.setObjectName("perceptronsSpBox")
        self.perceptronsLbl = QtWidgets.QLabel(Form)
        self.perceptronsLbl.setGeometry(QtCore.QRect(200, 42, 71, 16))
        self.perceptronsLbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.perceptronsLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.perceptronsLbl.setObjectName("perceptronsLbl")
        self.resultsGroupBox = QtWidgets.QGroupBox(Form)
        self.resultsGroupBox.setGeometry(QtCore.QRect(560, 20, 221, 101))
        self.resultsGroupBox.setObjectName("resultsGroupBox")
        self.mseLbl = QtWidgets.QLabel(self.resultsGroupBox)
        self.mseLbl.setGeometry(QtCore.QRect(20, 30, 81, 16))
        self.mseLbl.setObjectName("mseLbl")
        self.maeLbl = QtWidgets.QLabel(self.resultsGroupBox)
        self.maeLbl.setGeometry(QtCore.QRect(20, 50, 81, 16))
        self.maeLbl.setObjectName("maeLbl")
        self.meanLbl = QtWidgets.QLabel(self.resultsGroupBox)
        self.meanLbl.setGeometry(QtCore.QRect(110, 30, 101, 16))
        self.meanLbl.setObjectName("meanLbl")
        self.stdLbl = QtWidgets.QLabel(self.resultsGroupBox)
        self.stdLbl.setGeometry(QtCore.QRect(110, 50, 101, 16))
        self.stdLbl.setObjectName("stdLbl")
        self.timeLbl = QtWidgets.QLabel(self.resultsGroupBox)
        self.timeLbl.setGeometry(QtCore.QRect(20, 70, 151, 16))
        self.timeLbl.setObjectName("timeLbl")
        self.drawPlotsCbx = QtWidgets.QCheckBox(Form)
        self.drawPlotsCbx.setGeometry(QtCore.QRect(150, 70, 91, 20))
        self.drawPlotsCbx.setChecked(False)
        self.drawPlotsCbx.setObjectName("drawPlotsCbx")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):              # setting up text labels
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Chernyavskiy diploma"))
        self.saveWeightsBtn.setText(_translate("Form", "Save weights"))
        self.trainBtn.setText(_translate("Form", "Train && test"))
        self.batchSizeLbl.setText(_translate("Form", "Batch size:"))
        self.epochsLbl.setText(_translate("Form", "Epochs:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Form", "Train NN"))
        self.loadWeightsBtn.setText(_translate("Form", "Load weights"))
        self.predictBtn.setText(_translate("Form", "Predict"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Load weights"))
        self.outputLbl.setText(_translate("Form", "Output:"))
        self.loadDataBtn.setText(_translate("Form", "Load data"))
        self.perceptronsLbl.setText(_translate("Form", "perceptrons"))
        self.resultsGroupBox.setTitle(_translate("Form", "Results"))
        self.mseLbl.setText(_translate("Form", "MSE: 0.0000"))
        self.maeLbl.setText(_translate("Form", "MAE: 0.0000"))
        self.meanLbl.setText(_translate("Form", "Mean: 0.0000"))
        self.stdLbl.setText(_translate("Form", "Stdev: 0.0000"))
        self.timeLbl.setText(_translate("Form", "Training time: 0.00 sec"))
        self.drawPlotsCbx.setText(_translate("Form", "Draw plots"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

